name: ci

on:
  push:

env:
  BRANCH: dev-0-1-0-separate-saphe-from-satysfi

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # core-unix cannot be installed on windows
          - macos-latest # Intel Mac (x86_64)
          - macos-14 # Apple Silicon Mac (arm64)
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14
          allow-prelease-opam: true # to speed up
          opam-repositories: |
            satysfi-external: https://github.com/gfngfn/satysfi-external-repo.git
            default: https://github.com/ocaml/opam-repository.git
        if: matrix.os != 'windows-latest'
      # - uses: ocaml/setup-ocaml@v2
      #   with:
      #     ocaml-compiler: 4.14
      #     opam-repositories: |
      #       satysfi-external: https://github.com/gfngfn/satysfi-external-repo.git
      #       sunset: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
      #       default: https://github.com/ocaml/opam-repository.git
      #   if: runner.os == 'Windows'
      - run: git clone -b ${{ env.BRANCH }} https://github.com/gfngfn/SATySFi.git
      - run: opam pin add --no-action --dev-repo satysfi-util SATySFi
      - run: opam pin add --no-action --dev-repo satysfi-common SATySFi
      - run: opam pin add --no-action --dev-repo saphe SATySFi
      - run: opam pin add --no-action --dev-repo satysfi SATySFi
      - run: opam update
      - run: opam depext saphe satysfi
      - run: opam install saphe satysfi
      - run: cd SATySFi && ./install-libs.sh ~/.saphe install
      - run: |
          eval $(opam env)
          ldd $(which satysfi)
          ldd $(which saphe)
        if: runner.os == 'Linux'
      - run: |
          eval $(opam env)
          otool -L $(which satysfi)
          otool -L $(which saphe)
        if: runner.os == 'macOS'
      # TODO: check DLLs on Windows
      # - run:
      #   if: runner.os == 'Windows'
